<a href="https://colab.research.google.com/github/JoseLLoredoHdz/mineria/blob/main/MineriaDeDatos2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

#Primer parcial

###Introduccion

####Conceptos


Minería de Datos Es el proceso técnico y automatizado de explorar grandes volúmenes de datos históricos para descubrir patrones repetitivos, correlaciones ocultas o anomalías estadísticas que permiten describir y estructurar la información para entender qué sucedió en el pasado.

Ciencia de Datos Es el campo multidisciplinario que combina matemáticas, estadística y programación para gestionar todo el ciclo de vida de la información (recolección, limpieza y análisis), con el objetivo de extraer conocimiento profundo y construir modelos predictivos que permitan anticipar el futuro y fundamentar la toma de decisiones.

####Ciencia de Datos

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]

In [ ]:
L.insert?

In [ ]:
L?

In [ ]:
def cuadrado(a):
  """Devuelve el cuadrado de a."""
  return a ** 2

In [ ]:
cuadrado?

Acceder al código fuente con ??

In [ ]:
cuadrado??

In [ ]:
len??

Tabulación para completar el contenido del objeto, ctrl + barra_espacio

In [ ]:
L.

In [ ]:
import

In [ ]:
from itertools import co

In [ ]:
str.*find?

The Basics of NumPy Arrays


In [ ]:
import numpy as np


In [ ]:
np.random.seed(0)  # seed for reproducibility


In [ ]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print(x2.dtype)

int64


In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
#colocamos el indice del elemento a extraer , en este caso el primer elemento tiene el indice 0

In [ ]:
x1[0]

np.int64(5)

In [ ]:
x1[-1] #nos regresa el ultimo elemento del nArray

np.int64(9)

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0,0]

np.int64(3)

In [ ]:
x2[1,3]

np.int64(8)

In [ ]:
x2[0,0] = 12

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

####Estadistica basica

Media (Mean)


In [ ]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado


In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [ ]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [ ]:
mediana = np.median(data)


Varianza y Desviación Estándar


In [ ]:
varianza = np.var(data)
desviacion = np.std(data)

Generación de Datos Aleatorios

In [ ]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

Conclusión

NumPy facilita el análisis estadístico al proporcionar funciones optimizadas para cálculos comunes como media, mediana, varianza, desviación estándar y correlación. Además, ofrece herramientas para generar datos y analizar distribuciones.

Cuadros Estadisticos

In [1]:
import numpy as np
import pandas as pd
from io import StringIO


In [2]:
raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

In [3]:
# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

In [4]:
# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [5]:
df.head()

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True

In [6]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [8]:
edad[:5]

array([22., 21., 26., 21., 24.])

In [9]:
prog_py[:5]

array([ True,  True,  True,  True,  True])

In [11]:
# Descriptivos de edad (NumPy)
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),
    'p25': float(np.percentile(edad, 25)),
    'mediana': float(np.median(edad)),
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)),#varianza
    'std_muestral': float(np.std(edad, ddof=1)),#desviacion estandar
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),#coeficiente de variacion
}

In [12]:
summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [14]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

In [16]:
print(f"Frecuencias de utilizacion de python: {freq_python}")
print(f"Frecuencias de utilizacion de colab: {freq_colab}")
print(f"Frecuencias de utilizacion de github: {freq_gh}")

Frecuencias de utilizacion de python: {'Si': 54, 'No': 6}
Frecuencias de utilizacion de colab: {'Si': 18, 'No': 42}
Frecuencias de utilizacion de github: {'Si': 52, 'No': 8}


In [19]:
# Tablas cruzadas (NumPy)
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t


tab_py_colab = tabla2x2(prog_py, usa_colab)#sabe ...
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [21]:
print(f"Tabla 2x2 de Python y Colab: \n {tab_py_colab}")

Tabla 2x2 de Python y Colab: 
 [[ 6  0]
 [36 18]]


In [25]:
print(f"Tabla 2x2 de Python y Github: \n {tab_py_gh }")

Tabla 2x2 de Python y Github: 
 [[ 1  5]
 [ 7 47]]


In [22]:
# Medias de edad por grupo (NumPy)
means_by_group = {
    'edad_promedio_Python': {'Si': float(np.mean(edad[prog_py])) if np.any(prog_py) else np.nan,
                             'No': float(np.mean(edad[~prog_py])) if np.any(~prog_py) else np.nan},
    'edad_promedio_Colab':  {'Si': float(np.mean(edad[usa_colab])) if np.any(usa_colab) else np.nan,
                             'No': float(np.mean(edad[~usa_colab])) if np.any(~usa_colab) else np.nan},
    'edad_promedio_GitHub': {'Si': float(np.mean(edad[cuenta_gh])) if np.any(cuenta_gh) else np.nan,
                             'No': float(np.mean(edad[~cuenta_gh])) if np.any(~cuenta_gh) else np.nan},
}

summary_age, freq_python, freq_colab, freq_gh, tab_py_colab, tab_py_gh, tab_colab_gh, means_by_group

({'n': 60,
  'min': 20.0,
  'p25': 21.0,
  'mediana': 22.0,
  'media': 22.3,
  'p75': 23.0,
  'max': 26.0,
  'rango(ptp)': 6.0,
  'var_muestral': 1.8406779661016948,
  'std_muestral': 1.3567158752302173,
  'cv': 0.06083927691615324},
 {'Si': 54, 'No': 6},
 {'Si': 18, 'No': 42},
 {'Si': 52, 'No': 8},
 array([[ 6,  0],
        [36, 18]]),
 array([[ 1,  5],
        [ 7, 47]]),
 array([[ 5, 37],
        [ 3, 15]]),
 {'edad_promedio_Python': {'Si': 22.203703703703702, 'No': 23.166666666666668},
  'edad_promedio_Colab': {'Si': 22.11111111111111, 'No': 22.38095238095238},
  'edad_promedio_GitHub': {'Si': 22.21153846153846, 'No': 22.875}})