<a href="https://colab.research.google.com/github/JoseLLoredoHdz/mineria/blob/main/MineriaDeDatos2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

#Primer parcial

###Introduccion

####Conceptos


Minería de Datos Es el proceso técnico y automatizado de explorar grandes volúmenes de datos históricos para descubrir patrones repetitivos, correlaciones ocultas o anomalías estadísticas que permiten describir y estructurar la información para entender qué sucedió en el pasado.

Ciencia de Datos Es el campo multidisciplinario que combina matemáticas, estadística y programación para gestionar todo el ciclo de vida de la información (recolección, limpieza y análisis), con el objetivo de extraer conocimiento profundo y construir modelos predictivos que permitan anticipar el futuro y fundamentar la toma de decisiones.

####Ciencia de Datos

Ayuda y documentcion python

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]

In [ ]:
L.insert?

In [ ]:
L?

In [ ]:
def cuadrado(a):
  """Devuelve el cuadrado de a."""
  return a ** 2

In [ ]:
cuadrado?

Acceder al código fuente con ??

In [ ]:
cuadrado??

In [ ]:
len??

Tabulación para completar el contenido del objeto, ctrl + barra_espacio

In [ ]:
L.

In [ ]:
import

In [ ]:
from itertools import co

In [ ]:
str.*find?

IPython Magic Commands


In [ ]:
# El comando magico %timeit sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

86.2 µs ± 22.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#el comando magico %%timeit sirve tambien para evaluar el desempeño solo que
#este abarca varia lineas de codigo
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

90.5 µs ± 25.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

IPython and Shell Commands


In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data


/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
%cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
contents = !ls
print(contents)

['anscombe.json\t\t      mnist_test.csv', 'california_housing_test.csv   mnist_train_small.csv', 'california_housing_train.csv  README.md']


In [ ]:
directory = !pwd
print(directory)

['/content/sample_data']


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '09994f7cdef2',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

Understanding Data Types in Python

en python todo es objeto


In [ ]:
import numpy as np


In [ ]:
np.array([1, 4, 2, 5, 3])


array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
#podemos definir el tipo de dato que quieres
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')


array([1, 2, 3, 4])

In [ ]:
#genera un array bidimensional de esto
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Escalas de medicion

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 200

df = pd.DataFrame({
"id_cliente": range(1, n+1),
"genero": np.random.choice(["F", "M", "No binario", "Prefiero no decir"], size=n, p=[0.45, 0.45, 0.05, 0.05]),
"segmento": np.random.choice(["Estándar", "Oro", "Platino"], size=n, p=[0.6, 0.3, 0.1]),
"satisfaccion": np.random.choice([1,2,3,4,5], size=n, p=[0.1,0.2,0.35,0.25,0.1]),
"ciudad": np.random.choice(["SLP", "CDMX", "GDL", "MTY", "QRO"], size=n, p=[0.35,0.25,0.15,0.15,0.10]),
"edad": np.random.normal(35, 10, size=n).round(0).clip(18, 70).astype(int),
"ingreso_mensual": np.random.lognormal(mean=9.5, sigma=0.5, size=n).round(2), # pesos MXN aprox.
"temperatura_sala": np.random.normal(23, 2, size=n).round(1),
"visitas_ultimo_anio": np.random.poisson(lam=3, size=n),
"fecha_ultima_visita": pd.to_datetime("2025-12-31") - pd.to_timedelta(np.random.randint(0, 365, size=n), unit="D")
})

df.head()

id_cliente             genero  segmento  satisfaccion ciudad  edad  \
0           1                  F       Oro             2    SLP    27   
1           2  Prefiero no decir  Estándar             5    SLP    40   
2           3                  M  Estándar             3    SLP    54   
3           4                  M       Oro             4    SLP    48   
4           5                  F       Oro             3    SLP    51   

   ingreso_mensual  temperatura_sala  visitas_ultimo_anio fecha_ultima_visita  
0         10315.01              24.0                    4          2025-04-08  
1         27029.22              21.9                    1          2025-05-11  
2         42169.36              23.0                    3          2025-02-14  
3         11143.16              27.3                    4          2025-02-24  
4         10691.98              26.5                    6          2025-03-06

In [ ]:
# Nominal → category (sin orden)
df["genero"] = df["genero"].astype("category")
df["ciudad"] = df["ciudad"].astype("category")

# Ordinal → category con orden
segmento_cat = pd.CategoricalDtype(categories=["Estándar", "Oro", "Platino"], ordered=True)
df["segmento"] = df["segmento"].astype(segmento_cat)

satisfaccion_cat = pd.CategoricalDtype(categories=[1,2,3,4,5], ordered=True)
df["satisfaccion"] = df["satisfaccion"].astype(satisfaccion_cat)

# Intervalo / Razón → numérico (ya están), pero verifica:
df["temperatura_sala"] = pd.to_numeric(df["temperatura_sala"])
df["edad"] = pd.to_numeric(df["edad"])
df["ingreso_mensual"] = pd.to_numeric(df["ingreso_mensual"])
df["visitas_ultimo_anio"] = pd.to_numeric(df["visitas_ultimo_anio"])

# Derivada útil: días desde última visita (razón)
df["dias_desde_ultima_visita"] = (pd.to_datetime("2025-12-31") - df["fecha_ultima_visita"]).dt.days

In [ ]:
df.dtypes

3) Análisis descriptivo apropiado según escala
Nominal (frecuencias y proporciones):

In [2]:
freq_genero = df["genero"].value_counts().to_frame("frecuencia")
prop_genero = df["genero"].value_counts(normalize=True).round(3).to_frame("proporcion")
tabla_genero = freq_genero.join(prop_genero)
tabla_genero

NameError: name 'df' is not defined

Ordinal (distribución y tendencia central robusta — mediana):



In [ ]:
dist_satisfaccion = df["satisfaccion"].value_counts().sort_index().to_frame("frecuencia")
mediana_satisfaccion = df["satisfaccion"].astype(int).median() # convertir para calcular
dist_segmento = df["segmento"].value_counts().sort_index().to_frame("frecuencia")
mediana_satisfaccion, dist_satisfaccion, dist_segmento

Intervalo (media, desviación, pero cuidado con cero):



In [3]:
temp_stats = df["temperatura_sala"].agg(["mean", "std", "min", "max"]).round(2)
temp_stats

NameError: name 'df' is not defined

Razón (media, mediana, IQR, coeficiente de variación):



In [ ]:
def resumen_razon(s):
    return pd.Series({
    "n": s.count(),
    "media": s.mean(),
    "mediana": s.median(),
    "sd": s.std(),
    "min": s.min(),
    "q1": s.quantile(0.25),
    "q3": s.quantile(0.75),
    "max": s.max(),
    "cv": s.std()/s.mean() if s.mean()!=0 else np.nan
    }).round(2)

razon_stats = pd.concat({#otra manera de hacer un cuadro estadistico
    "edad": resumen_razon(df["edad"]),
    "ingreso_mensual": resumen_razon(df["ingreso_mensual"]),
    "visitas_ultimo_anio": resumen_razon(df["visitas_ultimo_anio"]),
    "dias_desde_ultima_visita": resumen_razon(df["dias_desde_ultima_visita"])
    }, axis=1)
razon_stats

4) Visualizaciones adecuadas por escala (opcional)


In [4]:
import matplotlib.pyplot as plt

# Nominal: barras
df["ciudad"].value_counts().plot(kind="bar", title="Frecuencia por ciudad")
plt.xlabel("Ciudad"); plt.ylabel("Frecuencia"); plt.show()

# Ordinal: barra ordenada por categorías
df["satisfaccion"].value_counts().sort_index().plot(kind="bar", title="Distribución de satisfacción (Likert)")
plt.xlabel("Puntaje"); plt.ylabel("Frecuencia"); plt.show()

# Intervalo: histograma de temperatura
df["temperatura_sala"].plot(kind="hist", bins=12, title="Histograma de temperatura (°C)")
plt.xlabel("°C"); plt.show()

# Razón: boxplot de ingreso (suele ser asimétrico)
df[["ingreso_mensual"]].plot(kind="box", title="Boxplot de ingreso mensual (MXN)")
plt.show()

NameError: name 'df' is not defined