<a href="https://colab.research.google.com/github/JoseLLoredoHdz/mineria/blob/main/MineriaDeDatos2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos

#Primer parcial

###Introduccion

####Conceptos


Minería de Datos Es el proceso técnico y automatizado de explorar grandes volúmenes de datos históricos para descubrir patrones repetitivos, correlaciones ocultas o anomalías estadísticas que permiten describir y estructurar la información para entender qué sucedió en el pasado.

Ciencia de Datos Es el campo multidisciplinario que combina matemáticas, estadística y programación para gestionar todo el ciclo de vida de la información (recolección, limpieza y análisis), con el objetivo de extraer conocimiento profundo y construir modelos predictivos que permitan anticipar el futuro y fundamentar la toma de decisiones.

####Ciencia de Datos

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]

In [ ]:
L.insert?

In [ ]:
L?

In [ ]:
def cuadrado(a):
  """Devuelve el cuadrado de a."""
  return a ** 2

In [ ]:
cuadrado?

Acceder al código fuente con ??

In [ ]:
cuadrado??

In [ ]:
len??

Tabulación para completar el contenido del objeto, ctrl + barra_espacio

In [ ]:
L.

In [ ]:
import

In [ ]:
from itertools import co

In [ ]:
str.*find?

The Basics of NumPy Arrays


In [1]:
import numpy as np


In [2]:
np.random.seed(0)  # seed for reproducibility


In [3]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print(x2.dtype)

int64


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
#colocamos el indice del elemento a extraer , en este caso el primer elemento tiene el indice 0

In [10]:
x1[0]

np.int64(5)

In [11]:
x1[-1] #nos regresa el ultimo elemento del nArray

np.int64(9)

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x2[0,0]

np.int64(3)

In [16]:
x2[1,3]

np.int64(8)

In [17]:
x2[0,0] = 12

In [18]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

####Estadistica basica

Media (Mean)


In [19]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado


In [20]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [21]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [22]:
mediana = np.median(data)


Varianza y Desviación Estándar


In [23]:
varianza = np.var(data)
desviacion = np.std(data)

Generación de Datos Aleatorios

In [24]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [26]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

Conclusión

NumPy facilita el análisis estadístico al proporcionar funciones optimizadas para cálculos comunes como media, mediana, varianza, desviación estándar y correlación. Además, ofrece herramientas para generar datos y analizar distribuciones.